name: Choice

on:
  push:
  workflow_dispatch:
    inputs:
      select:
        type: choice
        options:
        - One
        - Two

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.select }}
    - run: echo ${{ github.ref == 'refs/heads/main' && 'is main' || 'is not main' }}
