name: on-branch-push
on:
  push:
    branches-ignore:
    - 'main'
jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create PR
      run: |
        pr_url="$(curl --header "Authorization: token ${GITHUB_TOKEN}" --header 'Accept: application/vnd.github.v3+json' \
          'https://api.github.com/repos/petur/workflow-triggers/pulls?head=${{ github.ref }}' | jq -r '.[] | .url')"
        if [[ -n $pr_url ]]; then
          curl -X PUT --header "Authorization: token ${GITHUB_TOKEN}" --header 'Accept: application/vnd.github.v3+json' \
            "$pr_url" \
            --data "$(jq -n --arg branch ${{ github.ref }} '{ head: $branch, base: "main", title: "Test updated.", body: "This was a test." }')"
        else
          curl -X POST --header "Authorization: token ${GITHUB_TOKEN}" --header 'Accept: application/vnd.github.v3+json' \
            'https://api.github.com/repos/petur/workflow-triggers/pulls' \
            --data "$(jq -n --arg branch ${{ github.ref }} '{ head: $branch, base: "main", title: "Test", body: "This is a test." }')"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
